// Háttérkép
export const BACKGROUND_IMAGE_URL = "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=2053&auto=format&fit=crop";

// Beépített fix labor vizsgálatok (Mátészalka)
export const LAB_DATABASE = [
  {
    category: "Általános",
    items: [
      { id: "alt-1", name: "CRP", price: 1500, time: "1 munkanap" },
      { id: "alt-2", name: "AST (ASO)", price: 2200, time: "3 munkanap" },
      { id: "alt-3", name: "Vvt süllyedés", price: 1500, time: "1 munkanap" },
      { id: "alt-4", name: "Vérkép automatával", price: 1000, time: "1 munkanap" },
      { id: "alt-5", name: "Vérkép+reticulocyta", price: 2200, time: "1 munkanap" },
      { id: "alt-6", name: "Teljes vizelet ált+üledék", price: 1200, time: "1 munkanap" },
      { id: "alt-7", name: "Vizelet tenyésztés", price: 6000, time: "-" },
      { id: "alt-8", name: "Vércsoport", price: 15000, time: "2 munkanap" },
      { id: "alt-9", name: "Húgysav", price: 400, time: "1 munkanap" },
      { id: "alt-10", name: "Epesav", price: 10500, time: "8 munkanap" },
      { id: "alt-11", name: "Koleszterin", price: 400, time: "1 munkanap" },
      { id: "alt-12", name: "HDL-koleszterin", price: 700, time: "1 munkanap" },
      { id: "alt-13", name: "LDL koleszterin", price: 700, time: "1 munkanap" },
      { id: "alt-14", name: "Triglicerid", price: 400, time: "1 munkanap" },
      { id: "alt-15", name: "Vas", price: 500, time: "1 munkanap" },
      { id: "alt-16", name: "Transzferrin", price: 1000, time: "1 munkanap" },
      { id: "alt-17", name: "Transzferrin szat. (vas+transzf)", price: 300, time: "1 munkanap" },
      { id: "alt-18", name: "Ferritin", price: 2600, time: "1 munkanap" },
      { id: "alt-19", name: "Lipáz", price: 800, time: "1 munkanap" },
      { id: "alt-20", name: "Amiláz", price: 800, time: "1 munkanap" },
      { id: "alt-21", name: "Pancreas spec. elasztáz", price: 20000, time: "17 munkanap" },
      { id: "alt-22", name: "Albumin", price: 400, time: "1 munkanap" },
      { id: "alt-23", name: "Összfehérje", price: 400, time: "1 munkanap" },
      { id: "alt-24", name: "IgG", price: 2000, time: "3 munkanap" },
      { id: "alt-25", name: "IgA (Immunglobulin A)", price: 2000, time: "3 munkanap" },
      { id: "alt-26", name: "IgM", price: 2000, time: "3 munkanap" },
      { id: "alt-27", name: "Nagylabor", price: 12000, time: "-" },
    ]
  },
  {
    category: "Hemosztázis",
    items: [
      { id: "hem-1", name: "Prothrombin(INR)", price: 1000, time: "1 munkanap" },
      { id: "hem-2", name: "APTI", price: 1000, time: "1 munkanap" },
      { id: "hem-3", name: "Trombin idő", price: 1000, time: "1 munkanap" },
      { id: "hem-4", name: "Fibrinogén", price: 1700, time: "1 munkanap" },
      { id: "hem-5", name: "D-dimer", price: 6500, time: "1 munkanap" },
    ]
  },
  {
    category: "Májfunctio",
    items: [
      { id: "maj-1", name: "Összbilirubin", price: 400, time: "1 munkanap" },
      { id: "maj-2", name: "GPT", price: 400, time: "1 munkanap" },
      { id: "maj-3", name: "Alkalikus foszfatáz", price: 400, time: "1 munkanap" },
      { id: "maj-4", name: "GOT", price: 400, time: "1 munkanap" },
      { id: "maj-5", name: "GGT", price: 400, time: "1 munkanap" },
      { id: "maj-6", name: "LDH", price: 400, time: "1 munkanap" },
    ]
  },
  {
    category: "Vesefunkció",
    items: [
      { id: "vese-1", name: "Karbamid", price: 400, time: "1 munkanap" },
      { id: "vese-2", name: "Kreatinin", price: 500, time: "1 munkanap" },
    ]
  },
  {
    category: "Cukor és Anyagcsere",
    items: [
      { id: "cuk-1", name: "Glukóz- éhgyomri", price: 400, time: "1 munkanap" },
      { id: "cuk-2", name: "Hemoglobin A1c", price: 3500, time: "1 munkanap" },
      { id: "cuk-3", name: "Fruktózamin", price: 3000, time: "3 munkanap" },
      { id: "cuk-4", name: "Inzulin- éhgyomri", price: 2500, time: "1 munkanap" },
      { id: "cuk-5", name: "3 pontos vércukorterhelés", price: 1200, time: "1 munkanap" },
      { id: "cuk-6", name: "3 pontos inzulinterhelés", price: 7500, time: "1 munkanap" },
    ]
  },
  {
    category: "Ionok",
    items: [
      { id: "ion-1", name: "Nátrium", price: 400, time: "1 munkanap" },
      { id: "ion-2", name: "Kálium", price: 400, time: "1 munkanap" },
      { id: "ion-3", name: "Klorid", price: 400, time: "1 munkanap" },
      { id: "ion-4", name: "Calcium", price: 400, time: "1 munkanap" },
      { id: "ion-5", name: "Magnézium", price: 400, time: "1 munkanap" },
      { id: "ion-6", name: "P-foszfor", price: 400, time: "1 munkanap" },
      { id: "ion-7", name: "Cink", price: 6900, time: "3 munkanap" },
    ]
  },
  {
    category: "Allergia",
    items: [
      { id: "all-1", name: "Cöliacia", price: 6500, time: "5 munkanap" },
      { id: "all-2-a", name: "EMA IgA", price: 10000, time: "5 munkanap" },
      { id: "all-2-b", name: "EMA IgG", price: 10000, time: "5 munkanap" },
      { id: "all-3", name: "Nutritív 20", price: 23000, time: "5 munkanap" },
      { id: "all-4", name: "Nutritív 40", price: 28000, time: "5 munkanap" },
      { id: "all-5", name: "IgE", price: 4000, time: "3 munkanap" },
      { id: "all-6", name: "Hisztamin intolerancia (DAO)", price: 14000, time: "17 munkanap" },
      { id: "all-7", name: "40-es panel étel intolerancia", price: 22000, time: "3 munkanap" },
      { id: "all-8", name: "108-as intolerancia panel", price: 47000, time: "5 munkanap" },
      { id: "all-9", name: "Laktóz", price: 16000, time: "10 munkanap" },
      { id: "all-10", name: "Laktóz nyál", price: 16000, time: "10 munkanap" },
      { id: "all-11", name: "Inhalatív 20", price: 23000, time: "5 munkanap" },
      { id: "all-12", name: "Inhalatív 40", price: 32000, time: "5 munkanap" },
      { id: "all-13", name: "Méh-darázscs. antisepc. IgE", price: 16000, time: "5 munkanap" },
      { id: "all-14", name: "54 kombinált allergia panel", price: 33000, time: "-" },
    ]
  },
  {
    category: "Hormonok",
    items: [
      { id: "hor-1", name: "TSH", price: 2000, time: "1 munkanap" },
      { id: "hor-2", name: "fT3", price: 3000, time: "1 munkanap" },
      { id: "hor-3", name: "FT4", price: 3000, time: "1 munkanap" },
      { id: "hor-4", name: "Thyreoglobulin", price: 4000, time: "5 munkanap" },
      { id: "hor-5", name: "Anti TPO", price: 4000, time: "1 munkanap" },
      { id: "hor-6", name: "TRAK", price: 7500, time: "3 munkanap" },
      { id: "hor-7", name: "Anti thyreoglob. antitest (Anti TG)", price: 4000, time: "1 munkanap" },
      { id: "hor-8", name: "Reverz T3", price: 7500, time: "-" },
      { id: "hor-9", name: "FSH", price: 3500, time: "1 munkanap" },
      { id: "hor-10", name: "LH", price: 3000, time: "1 munkanap" },
      { id: "hor-11", name: "Prolactin", price: 3000, time: "1 munkanap" },
      { id: "hor-12", name: "Ösztradiol E2", price: 3000, time: "1 munkanap" },
      { id: "hor-13", name: "Progeszteron", price: 4800, time: "1 munkanap" },
      { id: "hor-14", name: "AMH", price: 11000, time: "3 munkanap" },
      { id: "hor-15", name: "Béta-HCG", price: 4500, time: "1 munkanap" },
      { id: "hor-16", name: "Tesztoszteron", price: 3500, time: "1 munkanap" },
      { id: "hor-17", name: "Total és szabad tesztoszteron", price: 8000, time: "1 munkanap" },
      { id: "hor-18", name: "Cortizol", price: 3500, time: "2 munkanap" },
      { id: "hor-19", name: "SHBG", price: 4000, time: "1 munkanap" },
      { id: "hor-20", name: "Parathormon (PHT)", price: 5500, time: "5 munkanap" },
      { id: "hor-21", name: "Aldoszteron", price: 11000, time: "17 munkanap" },
      { id: "hor-22", name: "C-peptid", price: 6500, time: "-" },
      { id: "hor-23", name: "DHEA-S", price: 3500, time: "1 munkanap" },
      { id: "hor-24", name: "CK", price: 600, time: "-" },
    ]
  },
  {
    category: "Tumormarker",
    items: [
      { id: "tum-1", name: "CA 125", price: 4600, time: "5 munkanap" },
      { id: "tum-2", name: "CA 19-9", price: 4000, time: "3 munkanap" },
      { id: "tum-3", name: "CA 72-4", price: 6500, time: "17 munkanap" },
      { id: "tum-4", name: "CA 15-3", price: 4500, time: "3 munkanap" },
      { id: "tum-5", name: "CEA", price: 4000, time: "3 munkanap" },
      { id: "tum-6", name: "ROMA index", price: 14000, time: "7 munkanap" },
      { id: "tum-7", name: "PSA", price: 3000, time: "1 munkanap" },
      { id: "tum-8", name: "PSA free", price: 4000, time: "1 munkanap" },
      { id: "tum-9", name: "NSE", price: 11000, time: "-" },
      { id: "tum-10", name: "TPA", price: 11000, time: "-" },
      { id: "tum-11", name: "AFP", price: 4500, time: "-" },
    ]
  },
  {
    category: "Vitaminok",
    items: [
      { id: "vit-1", name: "A vitamin", price: 12000, time: "17 munkanap" },
      { id: "vit-2", name: "B12 vitamin", price: 4000, time: "1 munkanap" },
      { id: "vit-3", name: "Folsav", price: 4000, time: "1 munkanap" },
      { id: "vit-4", name: "C vitamin", price: 15000, time: "17 munkanap" },
      { id: "vit-6", name: "Jód", price: 18000, time: "14 munkanap" },
      { id: "vit-7", name: "Szelén", price: 12000, time: "14 munkanap" },
      { id: "vit-8", name: "D-vitamin", price: 4500, time: "1 munkanap" },
      { id: "vit-9", name: "K1 vitamin", price: 18000, time: "17 munkanap" },
    ]
  },
  {
    category: "Fertőzés",
    items: [
      { id: "fer-1", name: "Hepatitis A (IgG+IgM) antitest", price: 6500, time: "3 munkanap" },
      { id: "fer-2", name: "Hepatitis A friss (IgM)", price: 4500, time: "1 munkanap" },
      { id: "fer-3", name: "Hepatitis B (HBsAg) antigén", price: 4500, time: "3 munkanap" },
      { id: "fer-4", name: "Hepatitis B antitest (Anti-HBsAg)", price: 4500, time: "3 munkanap" },
      { id: "fer-5", name: "Hepatitis B (Anti- HBcAg)", price: 5300, time: "3 munkanap" },
      { id: "fer-6", name: "Hepatitis C antitest", price: 5500, time: "3 munkanap" },
      { id: "fer-7-a", name: "Hepatitis E IgG", price: 12000, time: "10 munkanap" },
      { id: "fer-7-b", name: "Hepatitis E IgM", price: 12000, time: "10 munkanap" },
      { id: "fer-8", name: "Autoimmun májpanel", price: 13500, time: "-" },
      { id: "fer-9", name: "Borrelia antitest IgG+IgM (Lyme kór)", price: 20000, time: "7 munkanap" },
      { id: "fer-10", name: "Chlamydia pneum. anti. IGG IgM+IgA", price: 10000, time: "5 munkanap" },
      { id: "fer-11-a", name: "Clamidia tracho IgG", price: 10000, time: "5 munkanap" },
      { id: "fer-11-b", name: "Clamidia tracho IgA", price: 10000, time: "5 munkanap" },
      { id: "fer-11-c", name: "Clamidia tracho IgM", price: 10000, time: "5 munkanap" },
      { id: "fer-12-a", name: "Cytomegalovírus IgG", price: 6600, time: "3 munkanap" },
      { id: "fer-12-b", name: "Cytomegalovírus IgM", price: 6600, time: "3 munkanap" },
      { id: "fer-13", name: "Epstein-bar vírus antitestek", price: 10500, time: "5 munkanap" },
      { id: "fer-14", name: "Helicobacter pylori antit. IgA+IgG", price: 8000, time: "2 munkanap" },
      { id: "fer-15", name: "Herpes simplex vírus IgG+IgM", price: 12000, time: "5 munkanap" },
      { id: "fer-16", name: "HIV", price: 6500, time: "3 munkanap" },
      { id: "fer-17", name: "Legionella IgG, IgM", price: 15000, time: "17 munkanap" },
      { id: "fer-18", name: "Morbili (kanyaró) IgG", price: 9000, time: "17 munkanap" },
      { id: "fer-19", name: "Mycoplasma pneumoniae antit.", price: 10000, time: "5 munkanap" },
      { id: "fer-20", name: "Parvo vírus B19 IgG", price: 10000, time: "5 munkanap" },
      { id: "fer-21", name: "Rubeola védettség", price: 7500, time: "5 munkanap" },
      { id: "fer-22", name: "Rubeola vírus antit. IgG-IgM", price: 7500, time: "5 munkanap" },
      { id: "fer-23", name: "Toxoplasma antitest IgG-IgM", price: 7500, time: "3 munkanap" },
      { id: "fer-24", name: "Treponema ellenanyag (LUES)", price: 5500, time: "5 munkanap" },
      { id: "fer-25", name: "Varicella zoster védettség", price: 8500, time: "5 munkanap" },
      { id: "fer-26", name: "Varicella zoster vírus antit. IgG-IgM", price: 9000, time: "5 munkanap" },
    ]
  },
  {
    category: "Vegyes",
    items: [
      { id: "veg-1", name: "Spermium elleni antitest", price: 16000, time: "21 munkanap" },
      { id: "veg-2", name: "Leiden mutáció", price: 15000, time: "12 munkanap" },
      { id: "veg-3", name: "Calprotectin", price: 8000, time: "5 munkanap" },
      { id: "veg-4", name: "Széklet tenyésztés", price: 8500, time: "5 munkanap" },
      { id: "veg-5", name: "Széklet vér (3 minta)", price: 7500, time: "-" },
      { id: "veg-6", name: "Leptin", price: 15000, time: "-" },
      { id: "veg-7", name: "APC rezisztencia", price: 8000, time: "-" },
      { id: "veg-8", name: "ADH", price: 17500, time: "17 munkanap" },
      { id: "veg-9", name: "ACTH", price: 8000, time: "-" },
      { id: "veg-10", name: "Anti-DSdna", price: 6000, time: "-" },
      { id: "veg-11", name: "Celluláris immunstátusz", price: 31000, time: "-" },
      { id: "veg-12", name: "Celluláris Immunsátusz+NK funkció", price: 55000, time: "-" },
      { id: "veg-13", name: "NK lymphocyta funkció", price: 38000, time: "-" },
      { id: "veg-14", name: "220 intolerancia igg", price: 80000, time: "-" },
    ]
  }
];